### ISSUE TITLE
How is dot different from mul ?

### ISSUE THREAD

**Issue by ejackson** [mikera/core.matrix#11]
Isn't the doc product of two vectors the same as mul ?  Why is this a unique fn in the API ?

https://github.com/mikera/matrix-api/blob/master/src/main/clojure/core/matrix.clj#L249

**Comment by mikera** [comment]
A few reasons I thought to include it:
- I guess it depends on your exact definitions, but isn't the dot product of vectors x any y equal to the matrix product of transpose(x) and y? (see e.g.: http://mathinsight.org/dot_product_matrix_notation)
- It is probably worth providing both as a fast path - many libraries will do extremely fast dot products
- It is helpful to make code more readable - if you set `dot` then you know it is a vector rather than a matrix operation , will be more clear to mathematicians etc.

**Comment by ejackson** [comment]
OK, makes sense.
