### ISSUE TITLE
clash with cascalog

### ISSUE THREAD

**Issue by humanitiesNerd** [mikera/core.matrix#112]
If in a namespace I use both cascalog and matrix, like this

```
(:use clojure.core.matrix)
(:use cascalog.api)
```

I get

```
user=> (use 'my-namespace.operations)

IllegalStateException div already refers to: #'clojure.core.matrix/div in namespace: playground-rebuild.operations  clojure.lang.Namespace.warnOrFailOnReplace (Namespace.java:88)
user=> (quit)
```

**Comment by humanitiesNerd** [comment]
There's a "div" in cascalog.api

**Comment by mikera** [comment]
Yeah - though this is a generic problem with the way Clojure handles namespace clashes, not a core.matrix issue as such. FWIW, I think this should be a controllable warning rather than an error, but that's a problem for Clojure core team to sort out....

Using "require" with an alias is probably the best workaround.
