### ISSUE TITLE
Bug in slice implementation of nd-array and nd-wrapper

### ISSUE THREAD

**Issue by mschuene** [mikera/core.matrix#130]
The documentation of slice says:
Slicing a 1D vector will return a scalar.
However:
(scalar? (slice (matrix :ndarray [1 2 3]) 0)) ;=> false
(scalar? (slice (submatrix [1 2 3] [[0 2]]) 0)) ;=> false
Persistent vector is rightly returning a scalar here.
ndarray and ndwrapper return 0-dimensional arrays instead of scalars, but 
according to scalar?
"Returns true if the parameter is a scalar value (i.e. acceptable as matrix element value).
   A 0-d array containing a scalar is _not_ itself a scalar value."

**Comment by mikera** [comment]
I think this is a defect in the slice implementation for NDArray and NDWrapper. 

"slice" documentation is correct I think - we want slicing a vector to return scalars as the most natural expected behaviour. 

We have "slice-views" as a backup if you really want 0-dimensional array views for some reason....

**Comment by mschuene** [comment]
Added PR to fix this.
See https://github.com/mikera/core.matrix/pull/133
Build fails because the bug in vectorz.

**Comment by mikera** [comment]
Closing as this one is fixed now I think...
