### ISSUE TITLE
immutable not implemented for ndarray and persistent-vector

### ISSUE THREAD

**Issue by mars0i** [mikera/core.matrix#135]
``` clojure
user=> (immutable (matrix :vectorz [[1 2][3 4]]))
#<ImmutableMatrix [[1.0,2.0],[3.0,4.0]]>

user=> (immutable (matrix :persistent-vector [[1 2][3 4]]))
IllegalArgumentException No implementation of method: :immutable-matrix of protocol: #'clojure.core.matrix.protocols/PImmutableMatrixConstruction found for class: clojure.lang.PersistentVector  clojure.core/-cache-protocol-fn (core_deftype.clj:544)

user=> (immutable (matrix :ndarray [[1 2][3 4]]))
IllegalArgumentException No implementation of method: :immutable-matrix of protocol: #'clojure.core.matrix.protocols/PImmutableMatrixConstruction found for class: clojure.core.matrix.impl.ndarray.NDArray  clojure.core/-cache-protocol-fn (core_deftype.clj:544)
```

**Comment by mars0i** [comment]
I've added a pull request that fixes this for persistent-vector.  Am I right in thinking that ndarray is a mutable-only implementation?  So `immutable-matrix` on an ndarray matrix should return a vectorz-clj or persistent-vector matrix?

**Comment by mikera** [comment]
Hi this should probably have a default implementation that does the following:
- tests if the array is already immutable
- if so, return it unchanged
- if not, coerce to nested persistent vectors

That should fix it for all arrays that don't directly implement the immutable-matrix protocol

**Comment by mars0i** [comment]
Mikera pointed out that my pull request didn't fully resolve the issue for persistent-vector, because a persistent vector can contain mutable submatrices, and the code in the pull request just returns a persistent-vector as is:

``` clojure
user=> (def v (matrix :vectorz [1 2 3]))
#'user/v
user=> (mutable? v)
true
user=> (def p [v v])
#'user/p
user=> (mutable? p)
false
user=> p
[#<Vector [1.0,2.0,3.0]> #<Vector [1.0,2.0,3.0]>]
user=> (def i (immutable p))
#'user/i
user=> i
[#<Vector [1.0,2.0,3.0]> #<Vector [1.0,2.0,3.0]>]
user=> (mset! (get-row i 0) 0 25)
nil
user=> i
[#<Vector [25.0,2.0,3.0]> #<Vector [25.0,2.0,3.0]>]
user=> (mset! i 0 0 -1)

IllegalArgumentException No implementation of method: :set-2d! of protocol: #'clojure.core.matrix.protocols/PIndexedSettingMutable found for class: clojure.lang.PersistentVector  clojure.core/-cache-protocol-fn (core_deftype.clj:544)
```

But if the persistent vector with embedded mutable vectors isn't satisfactory as a return value of `immutable`, I wonder whether should `mutable?` also check inside a persistent-vector for mutable components?  Or should anything that's a persistent vector count as immutable because you can't modify it unless you pull something out from inside it?  (That does seem dangerous, as the example illustrates.)

**Comment by mikera** [comment]
I guess immutable on a persistent vector should recursively check for mutability, and if it finds any then `assoc` in the result of calling `immutable` on the relevant sub-component. 

Should be a simple recursive reduce operation..... 

I don't particularly like the fact that it is O(n) in the number of elements though I think that is unavoidable if we actually want to guarantee immutability, since we don't know what the persistent vector might contain.

**Comment by mars0i** [comment]
I might be raising issues that have already been settled here, but I'm just thinking out loud, so to speak:  Mixed matrices can only be created by going outside of core.matrix, i.e. creating persistent vectors directly, without calling `matrix` or some other core.matrix function, right?  Could it be reasonable to say "Yes, it's fine to use persistent vectors in ways not explicitly supported, but then you're on your own."  In particular, you won't be able to trust `immutable` and  `mutable?`.

Is it guaranteed that matrix operations such as multiplication will work on mixed matrices?  Is it important to support that?  Then maybe `immutable` and `mutable?` have to check inside persistent vectors.  But this means that what one would think would be constant time, fast operations can be slower than you'd think.

**Comment by mikera** [comment]
This hasn't been finally settled. 

However note that mixed matrices can be created in all sorts of ways in fairly normal Clojure code, some of which can't really be counted as valid matrices, some of which are a bit ambiguous. Consider:

``` clojure
[(double-array 3) (double-array 3)] ;; a mutable 2x3 matrix??

[1 [1 3]]   ;; maybe invalid? but could be a length 2 vector containing a long and a vector?

[(atom 1) (atom 2)]   ;; an immutable vector of 2 atoms? Or a mutable vector of two longs?
```

A fundamental problem with nested vectors is ultimately that they don't have much in the way of enforceable constraints on what people put in them. That means that:
- We have to be pretty careful about the assumptions we make
- Any time we want to be sure about structure is an O(n) cost

Personally I think vectors are great for simple cases but should be mildly discouraged for more complex work, they don't really have the performance or safety guarantees that we would like in a full array implementation. That's why we have things like `NDArray`, `Vectorz` and `Clatrix`....

**Comment by mschuene** [comment]
[1 [1 3]] There is the question if a vector can have any object as elements or if it can't have seq-able elements as scalars. (This could also mean that one needs to have generic versions of shape etc which allow sequential scalar types)

Maybe we could use metadata to get the shape of a persistent array?

**Comment by mikera** [comment]
I think seqs as scalars is pushing the limits of what we can do with persistent vectors / other nested models - you really need NDArray or similar if you want to support that.

I thought about metadata before - it's an interesting idea but I avoided it for a couple of reasons:
- You have to handle the no-metadata case anyway. So you still have to write the shape-walking code.
- It adds a bit of extra performance overhead (both for the metadata checks and the extra memory objects)

**Comment by mikera** [comment]
Closing this as I think it is fixed now
