### ISSUE TITLE
PImplementation

### ISSUE THREAD

**Issue by siscia** [mikera/core.matrix#16]
Hi,

I do have some question about the new PImplementation, what should come out of new-vector, new-matrix and new-matrix-nd ???

Should come out another vector, and other matrixs ?

There is really a point doing so ?

I mean, it bring to do something like this...

``` clj
(def matrix (matrix [[1 2] [2 1]]))
(new-vector matrix [1 2 3 4])
```

To get a vector... Why we need to put the first matrix in the call new-vector ???
To have the same implementation of vector ?

Am I missing something ?

I will make something like define new-vector-parallel-colt, new-matrix-parallel-colt, and then a big case statement

``` clj
(defn new-vector [data & {:keys [type :or type :parrallel-colt]}]
  (case type
    :parallel-colt (new-vector-parallel-colt data)
    :other (new-vector-other data)))
```

Sorry if I am missing the obvious...

**Comment by mikera** [comment]
The idea is to allow for generic matrix construction. See how it is implemented in vectorz-clj if you like:
- https://github.com/mikera/vectorz-clj/blob/master/src/main/clojure/mikera/vectorz/matrix_api.clj

In general, can you ask this kind of question on the Numerical Clojure discussion list rather than a GitHub issue? It's a better place for this kind of discussion.
- https://groups.google.com/forum/#!forum/numerical-clojure

Also be aware that we are still at experimental stage, so all of this is subject to change :-)
