### ISSUE TITLE
 dataset-from-columns seems to actually get rows

### ISSUE THREAD

**Issue by daslu** [mikera/core.matrix#198]
clojure.core.matrix.impl.dataset/dataset-from-columns
actually redefines its columns as rows (using clojure.core.matrix.protocols/get-rows).

https://github.com/mikera/core.matrix/blob/50939239de23c3302711ab4ae4358cc660b231cb/src/main/clojure/clojure/core/matrix/impl/dataset.clj#L21

Is it a mistake?

**Comment by Gerrrr** [comment]
Thank you for your code review.
. 
`clojure.core.matrix.impl.dataset/dataset-from-columns` gets `seq` of column names and `seq` of dataset columns as arguments. So that "rows" (0-dimension slices) of the second argument are actually "columns" of the dataset to be created. As dataset implementation is column-based and columns should be stored in `PersistentVector`, this is simply a way to extract them.

**Comment by mikera** [comment]
`dataset-from-columns` isn't meant to be a public function at present (it is in the `impl` namespace)

I think the dataset stuff needs some more experimentation to make sure we get the docs just right.

@Gerrrr - looking at some of the dataset constructurs I think the column names should generally be the second argument, after the main data argument. Do you agree?

**Comment by daslu** [comment]
Thanks, now I see (and it does work in small test cases). Sorry..

**Comment by mikera** [comment]
No worries @daslu - it is good to have your input! If you think this is something that is useful, it may be worth promoting to a public API

**Comment by daslu** [comment]
Thanks. The public API seems rich enough in my current experiments.

**Comment by Gerrrr** [comment]
> looking at some of the dataset constructurs I think the column names should generally be the second argument, after the main data argument. Do you agree?

Yes, I think you are right, that would be consistent with the rest of public API.
