### ISSUE TITLE
`count` not supported on type NDWrapper

### ISSUE THREAD

**Issue by scottdw** [mikera/core.matrix#205]
Not sure if this is an issue with `core.matrix` or the implementation of `core.matrix.stats/variance`.

``` clojure
(require '[clojure.core.matrix :as mat]) ;; => nil
(require '[clojure.core.matrix.stats :as mstats]) ;; => nil
(mstats/variance (mat/identity-matrix 2)) ;; => #<NDArray [0.5 0.5]>
(mstats/variance (mat/submatrix (mat/identity-matrix 2) 0 2 0 2)) ;; => UnsupportedOperationException count not supported on this type: NDWrapper  clojure.lang.RT.countFrom (RT.java:556)
```

Is `count` considered part of the matrix API and how much of the matrix API are submatrices expected to implement?

**Comment by mikera** [comment]
`count` isn't guaranteed to exist for an arbitrary core.matrix array (since core.matrix supports arbitrary array types, and `count` isn't extensible to arbitrary types).

So looks like a bug in c.c.m.stats to me, specifically this line: https://github.com/clojure-numerics/core.matrix.stats/blob/develop/src/main/clojure/clojure/core/matrix/stats.clj#L47

**Comment by mikera** [comment]
I've fixed this specific issue by implementing clojure.lang.Indexed on the NDWrapper

**Comment by scottdw** [comment]
I see you have also updated `core.matrix.stats`, thanks!
