### ISSUE TITLE
immutable function type parameter?

### ISSUE THREAD

**Issue by carocad** [mikera/core.matrix#264]
Hey guys,
First of all I'm not fully sure if this issue should be in this repo or in the vectorz-clj.
My issue/question is regarding the "immutable" function of core.matrix. According to the documentation it says that two parameters can be passed; data and type. Obviously data is the matrix that I want to make immutable but what is type? is this a documentation bug or is it right? because when I checked the vectorz-clj implementation of that protocol, only the data parameters was being passed.

Also if possible I would like to know if the immutable function does the job in O(1) time as with the transient/persistent Clojure equivalent or does it create a complete new matrix? I ask this because if a person took the job of creating a mutable matrix and then making it immutable, then that person is obviously interested in performance.

thanks in advance

**Comment by mikera** [comment]
The type currently isn't used.... the intention was to make it possible to specify a specific element type (e.g. doubles). However behaviour is likely to be implementation specific so I'm actually not sure if we should even keep this as an option.

I would suggest not using `type` for now.

**Comment by carocad** [comment]
Ok I understand your intention to keep it for future usage but shouldn't there be a comment or something on the documentation stating its lack of implementation? A person unnaware of this might this that there will be a gain on performance by passing a type.

Also, could you please tell me if there is a cost in changing a structure from its mutable to its immutable state?

**Comment by mikera** [comment]
Yeah, I'll add some notes and/or remove the type argument when I get a chance. Leaving this issue open as a reminder to do that.

Changing from mutable to immutable will usually have a moderate cost because you need to defensive copy the mutable data. 

There are a couple of ways to avoid this, but they are usually going to be implementation specific, e.g. in Vectorz you can do `(ImmutableMatrix/wrap mutable-matrix)` which will re-use the underlying data array. Caveat emptor of course: if you subsequently mutate the mutable matrix then obviously this will modify your "immutable" matrix. Only do this if you know the mutable matrix will never again be modified.

**Comment by mikera** [comment]
I've removed the redundant parameter for the moment, will be absent in next release. Thanks for the report!
