### ISSUE TITLE
Access element at index i of vector

### ISSUE THREAD

**Issue by michaellindon** [mikera/core.matrix#304]
If I have a vector v of type _mikera.vectorz.Vector_ , then how do I access the value at the i'th index? I cannot find it in the documentation at all. I have tried _nth_ and _get_ but these do not work. Looking through the source code I eventually was able to achieve what I want with (.get v i) where i is an integer but I'm wondering if this is the idiomatic way of accessing elements of a vector.

**Comment by mars0i** [comment]
`(mget v i)` is better, since it should work with any core.matrix implementation.  

(You might already know this, but you can also ask questions about core.matrix in the numerical-clojure Google group.)

**Comment by michaellindon** [comment]
I didn't know I could post questions there, thank you :)

I am using incanter which supposedly uses core.matrix with the vectorz implementation to handle the linear algebra. A minimal example looks like this:

```
(use '(incanter core stats charts))
(def values (sample-normal 10))
(type values)
(mget values 2)
```

values is of type mikera.vectorz.Vector but mget results in:

CompilerException java.lang.RuntimeException: Unable to resolve symbol: mget in this context, compiling:(/home/michael/combtest/src/combtest/core.clj:1:5)

I am surprised that mget doesn't get pulled in when using incanter

**Comment by mars0i** [comment]
Ah, OK.  You'll need to load core.matrix explicitly to use core.matrix functions that Incanter doesn't give you.  If Incanter exposed everything anyone might want from core.matrix, that would be a lot!  As it is, Incanter divides up its functions into different namespaces that the first line of your code loaded (`incanter.core`, `incanter.stats`, `incanter.charts`).  Think of core.matrix as one more namespace to load, but in a separate line because it's not part of Incanter.

It looks you're working in the REPL in the example above.  For that, I'd suggest either:

```clojure
(use 'clojure.core.matrix)
(mget values 2)
```
or
```clojure
(require '[clojure.core.matrix :as m])
(m/mget values 2)
```

In a source file, it's better to load core.matrix using `:require` inside an `ns` statement at the top of the file. 

You probably noticed that there's more documentation for core.matrix linked off of the main page of this repo, but feel free to ask questions in the numerical-clojure group.

**Comment by michaellindon** [comment]
Thank you so much @mars0i ! Makes sense :) Thanks for helping me get up and running with this, its my first foray into clojure. I'll check out the google group too. :+1:
