### ISSUE TITLE
Convention on return value of mutating operations

### ISSUE THREAD

**Issue by si14** [mikera/core.matrix#44]
Is there any particular reason why mutations doesn't return mutated object in default implementation? (assign! in impl/default.clj at line 187, for example)

**Comment by mikera** [comment]
Not particularly. They can but don't need to since the API functions in `clojure.core.matrix`do it for them, e.g.:

``` clojure
(defn assign!
  "Assigns a value to a matrix.
   Returns the mutated matrix"
  ([m a]
    (mp/assign! m a)
    m))
```

**Comment by si14** [comment]
Then there is a little discrepancy here for matrix implementers, because in implementations we often use protocols (and default implementations) that don't return values after mutating.

**Comment by mikera** [comment]
Very true. Do you think that is a problem?

I had intended the return value to be just a convenience for API end users, but we could always do it protocol implementations as well if that is helpful.

Total consistency between protocols and API is not practically achievable anyway, since there are things like variadic functions that aren't supported by protocols.
