### ISSUE TITLE
Move protocols into separate namespace

### ISSUE THREAD

**Issue by mikera** [mikera/core.matrix#5]
Maybe protocols should be moved into a separate namespace:

Pros:
- Hide protocols from API users
- Allow protocols to be used independently of core.matrix
- Might solve circular dependency issues with default implementations (core.matrix requires default implementation requires protocol)

**Comment by heffalump** [comment]
Playing devils advocate for a second, couldn't the default implementation be moved into core.matrix?  (I'm sort of assuming that the persistent vector implementation would be the default, since it would be the only one with no external dependencies.)  And if it were moved into core.matrix, there wouldn't be a circular dependency problem.

That said, moving the protocols into a separate namespace is likely the cleanest way to go about this.

**Comment by mikera** [comment]
Hmmm actually I'm writing a rough NDArray implementation, so we will have at least 2 default implementation options :-)

Yes we could put everything in core.matrix... though for some reason huge namespaces always feel a bit uncomfortable to me. It feels like sooner or later we will want protocols in a separate namespace. I note that clojure.core does it this way too..... so presumably it's not too absurd an idea!

So we might as well do the separation early rather than let people get confused and start using the protocols directly as part of the public API?

**Comment by mikera** [comment]
OK done this and pushes to master.... seems to work pretty well so I think an improvement on average
