### ISSUE TITLE
.toString broken for NDArray?

### ISSUE THREAD

**Issue by mikera** [mikera/core.matrix#50]
Currently .toString appears to be broken for NDArray (latest develop branch)

``` clojure
(def m (new-array :ndarray [3 3]))
(.toString m)
RuntimeException Can't coerce to vector: class clojure.core.matrix.impl.ndarray.NDArray  clojure.core.matrix.protocols/persistent-vector-coerce (protocols.clj:489)
```

**Comment by si14** [comment]
It seems that it's a bug in a core.matrix itself.

protocols.clj, line 487:
`(sequential? x) (mapv convert-to-nested-vectors x)`
it seems that this should be:
`(instance? clojure.lang.Seqable x) (mapv convert-to-nested-vectors x)`
because Sequential is not about being able to make a seq from object [1](https://groups.google.com/forum/#!topic/clojure/8YOs6Z1obP0). However, NDArray is obviously Sequential, too, so I'll mark it so.

However, this bug masked another bug, seemingly in NDArray itself. I'm investigating it.

**Comment by si14** [comment]
Never mind, that was not a bug of me and not of NDArray :)

**Comment by si14** [comment]
I've added a test for `toString` in compliance testing and it revealed that toString is also broken for wrappers, so I've just pushed the fix.

**Comment by mikera** [comment]
Cool thanks!

I'll give it a bit of poking. I think we need a few more compliance tests in general now that the variety of implementations is getting a bit more complex, so I'll probably add a few more tonight.

**Comment by si14** [comment]
Is this issue effectively closed?

**Comment by mikera** [comment]
Yes... the specific bug is fixed and has tests, so the issue is closed. The broader point about needing some more comprehensive compliance tests still stands, but that's not part of this issue :-)
