### ISSUE TITLE
Make NDArray into default implementation

### ISSUE THREAD

**Issue by mikera** [mikera/core.matrix#53]
Currently the core.marix default implementation is `:persistent-vector`

We should switch this to `:ndarray` once we are comfortable with the robustness of the NDArray implementation.

Dmitry - important milestone for you during GSoC, I think!

**Comment by mikera** [comment]
It would be good to complete this in advance of the next core.matrix release, ideally early next week. Dmitry can you take a look at this?

We are mostly there but some edge cases will need addressing: I think there are problems to solve with (at least):
- Matrix printing (pm and friends)
- Initialisation of new arrays (nils vs. zeros)
- Semantics of slicing down to scalars

**Comment by si14** [comment]
I've checked points in your list, here is what I've found out:
- matrix pretty-printing works fine if seq on 1d NDArray returns scalars;
- I've prepared, but commented out code for zeroing Object-based NDArray because there are explicit tests for nils in freshly created NDArray. Do I need to fix tests or remove zeroing? What type makes most sense for filling an array (I've implemented this with Double)?
- for this release I've made seq return scalars on 1d vectors. I think it's more consistent with other implementations and makes pretty-printing work without modification. We can change it later if we will decide so in the mail list.

**Comment by mikera** [comment]
Sounds sensible.

Zeroing object-based NDArrays is tricky: I think the default value should actually be nil. This is consistent with object array types in Java and most other languages.

OTOH, initialisation of numerical vectors and matrices would normally be zero-filled.

So we actually seem to have two different possible default values depending on the type of array required. Perhaps we should reflect this through different creation functions:
- `new-matrix` and `new-vector` should return zero-filled arrays (since they are directly intended to produce numeric matrices and vectors)
- `array` and `new-array` should return nil-filled arrays

**Comment by si14** [comment]
Done in 96f8e975.

**Comment by mikera** [comment]
OK great - I'm fine if you want to switch the default `*matrix-implementation*` over to NDArray (assuming all tests pass)

**Comment by si14** [comment]
Done in cd3d1746.

**Comment by mikera** [comment]
OK all looks good!
