### ISSUE TITLE
equals not working for different-sized NDArrays

### ISSUE THREAD

**Issue by mikera** [mikera/core.matrix#58]
``` clojure
(equals (array :ndarray 1) (array :ndarray [1 1]))
=> true
```

I believe these should be non-equal : different shaped arrays should not be equal to each other (even if the broadcasted version would be)

**Comment by si14** [comment]
Fixed in 7d6169a , this was an issue with default implementation. While fixing I've found a following problem: we don't specify what should be returned from `get-shape`, so NDArray returns PersistentVector and sparse map returns primitive array. It's a trouble, because in this case `(= (get-shape a) (get-shape b))` returns false even for identically-shaped matrices: `(= (long-array [1 2]) [1 2]) ;; false`.

**Comment by mikera** [comment]
Cool stuff.

`get-shape` is tricky - currently the only requirement is that it returns something that can be cast into a sequence i.e. so that `(vec (get-shape m))` is guaranteed to work. 

In the public API it's much simpler: `c.c.m/shape` always returns a Clojure vector.

Perhaps the internal representation should be revisited, but the idea was that different implementations might have different efficient native shape representations.

**Comment by si14** [comment]
OK, then it's done, I suppose.

**Comment by mikera** [comment]
Yep sounds good, I'll close it now.
