### ISSUE TITLE
what does coerce-param in protocols do?

### ISSUE THREAD

**Issue by Quantisan** [mikera/core.matrix#9]

**Comment by mikera** [comment]
It's intened to allow a matrix implementation to try and convert a matrix into a format it understands.

So for example:

``` clojure
(coerce-param vectorz-matrix jblas-matrix)
```

This gives the vectorz implementation a chance to do something clever with a JBLAS matrix, if it knows how.

It's called currently by the `coerce` function in core/matrix.clj, which adds extra handling for the case where coerce-param doesn't work.

**Comment by Quantisan** [comment]
how does it differ from type conversion? like converting a vectorz into a jblas object.

**Comment by mikera** [comment]
It's a tool to enable type conversion. Consider trying to convert the Vectorz matrix into something compatible with JBLAS:

``` clojure
(coerce-param jblas-matrix vectorz-matrix)
```

This gives the implementer three (I think!) options:
- Return the vectorz-matrix as-is. This means that you "understand" the vectorz matrix natively, and are happy to have vectorz matrices passed to JBLAS. An option if you want to write specialised matrix-matrix functions against another library (but probably too much work for most matrix implementations)
- Convert to a JBLAS object. You might, for example, note that vectorz has a fast operation to write out it's contents to a double[] array, and exploit this to enable an optimised conversion to a JBLAS object. Requires you to know about the other matrix type.
- Return nil - meaning "I don't know how to convert this"

Maybe this protocol can be made optional.... I provided it as a helpful tool rather than anything else.

**Comment by mikera** [comment]
Closing this since question seems to be answered and no more activity.
